name: Deploy Azure VMs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-linux-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: 1b3d2222-73ee-41e7-8dba-ccd549aa2469
          tenant-id: c64cd139-e40e-4967-bc0b-1a72021890af
          subscription-id: 80a31f80-0116-4fe0-acf5-ccaae10138a8

      - name: Provision Linux VM
        run: |
          az group create --name rg-github-vm-demo --location southafricanorth
          az vm create \
            --resource-group rg-github-vm-demo \
            --name vm Linux \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --generate-ssh-keys

  deploy-windows-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: 1b3d2222-73ee-41e7-8dba-ccd549aa2469
          tenant-id: c64cd139-e40e-4967-bc0b-1a72021890af
          subscription-id: 80a31f80-0116-4fe0-acf5-ccaae10138a8

      - name: Provision Windows VM
        run: |
          az group create --name rg-github-vm-demo --location southafricanorth
          az vm create \
            --resource-group rg-github-vm-demo \
            --name vm Windows \
            --image Win2022Datacenter \
            --public-ip-sku Standard \
            --admin-username azureuser \
            --admin-password '${{ secrets.VM_ADMIN_PASSWORD }}'
